services:
  nestapp:
    build: ./
    ports:
      - '3000:3000'
    env_file:
      - .development.env
    environment:
      DB_HOST: postgresdb
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_NAME: ecommerce
    depends_on:
      postgresdb:
        condition: service_healthy

  postgresdb:
    image: 'postgres'
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .development.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
